### ISSUE TITLE
Issue with this project

### ISSUE THREAD

**Issue by jonexume** [learn-co-curriculum/js-functions-lab#26]
I believe there is something wrong with the learn IDE.  I submitted this and its telling me I am wrong when I believe that I am correct.  I verified in QA section and someone with the identical code passed.  Please advise.

function happyHolidays() {
return `Happy holidays!`
}

function happyHolidaysTo(name) {
  return `Happy holidays, ${name}!`
}

function happyHolidaysTo(holiday name) {
  return `Happy ${holiday}, ${name}!`
}

function holidayCountdown(days holiday) {
return `It's ${days} days until ${holiday}!`
}

**Comment by maxwellbenton** [comment]
Hi @jonexume,

Sorry to hear you had trouble with this lab. We've updated the instructions to provide better guidance, specifically around template literals. Your code looks close to correct. I can't verify based on your comment, but it seems like you may have used single or double quotes around each returned string, rather than backticks. 

The updated instructions go into additional examples of how to use template literals to help ensure future students will not face the same problem as you encountered.

We apologize for any frustration this may have caused, but we appreciate you taking the time to provide feedback!
