### ISSUE TITLE
Why is my code failing the local tests? 

### ISSUE THREAD

**Issue by VictorLuo920** [learn-co-curriculum/js-functions-lab#27]
function happyHolidays() {
  return "Happy holidays!";
}

function happyHolidaysTo(name) {
  return "Happy holidays, ${name}!";
}

function happyHolidayTo(holiday, name) {
  return 'Happy ${holiday}, ${name}!';
}

function holidayCountdown(holiday, days) {
  return "It's ${days} days, until ${holiday}!";
}

**Comment by maxwellbenton** [comment]
Hi @VictorLuo920, 

We've updated the instructions to provide better guidance, specifically around template literals. Your code looks close to correct, but it looks like you used single or double quotes around each returned string, rather than backticks. 

The updated instructions go into additional examples of how to use template literals to help ensure future students will not face the same problem that you encountered.

We apologize for any frustration this may have caused, but we appreciate you taking the time to provide feedback!
