### ISSUE TITLE
what do I write in function and return 

### ISSUE THREAD

**Issue by rajanpatel1011** [learn-co-curriculum/js-functions-lab#35]
its always show me output with ${xxx}
instead of value itself

**Comment by maxwellbenton** [comment]
Hi @rajanpatel1011,

Sorry to hear that you were having difficulty with this lab. We've updated this lesson's instructions to include additional information on template literals and included additional examples of their syntax to help ensure future students will not face the same problem that you encountered. In your case, it looks like you may have used single or double quotes rather than backticks to wrap the template literal. 

We apologize for any frustration this may have caused, but we appreciate you taking the time to provide feedback!
