### ISSUE TITLE
Issue w/Functions Lab

### ISSUE THREAD

**Issue by brandong1** [learn-co-curriculum/js-functions-lab#36]
The second function description says:
Write a function named happyHolidaysTo. This function should accept a parameter of the name of the person you want to wish happy holidays, and **_return the string `Happy holidays, ${name}!`_**

1) functions happyHolidaysTo(name) returns "Happy holidays, ${name}!":

      Error: Expected 'Happy holidays, ${name}!' to equal 'Happy holidays, you!' 

      + expected - actual

      -Happy holidays, ${name}!
      +Happy holidays, you! //No mention of 'Happy holidays, you!' anywhere in this lab, but that's the correct answer to get the test to pass. Is this a mistake, or am I just a noob and missing something?

      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toEqual (node_modules/expect/lib/Expectation.js:81:30)
      at Context.it (test/index-test.js:12:38)

**Comment by brandong1** [comment]
Disregard.

I just discovered the joy of the index-test.js file...

**Comment by dmoniques** [comment]
Hello.  I'm now having the same issue and haven't figured out what to do in index-test.js.  If you get this message, please help!

**Comment by maxwellbenton** [comment]
Hi @brandong1,

We've updated the instructions to provide better guidance, specifically around template literals. The updated instructions go into additional examples of the required syntax to help ensure future students will not face the same problem that you encountered. In your case, it looks like you were nearly there, but just needed to use backticks rather than single or double quotes to wrap the template literal.

We apologize for any frustration this may have caused, but we appreciate you taking the time to provide feedback!
