### ISSUE TITLE
js-functions-lab

### ISSUE THREAD

**Issue by braj011** [learn-co-curriculum/js-functions-lab#39]
Not sure why only 1 of 4 tests is passing in the Functions lab.

After trying a few different things, current failing code in the index.js is:

function happyHolidaysTo(name) {
  return 'Happy holidays, ${name}'
}
happyHolidaysTo(you)

function happyHolidayTo(holiday, name) {
  return "Happy ${holiday}, ${name}"
}

function holidayCountdown(days, holiday) {
  return "It's ${days} days until ${holiday}!"
}

Can anyone assist? 
Thanks very much,

Bobby

**Comment by maxwellbenton** [comment]
Hi @braj011,
 
We've updated the instructions to provide better guidance, specifically around template literals. Your code looks close to correct, but it looks like you used single or double quotes around each returned string, rather than backticks.

The updated instructions go into additional examples of how to use template literals and the syntax required to help ensure future students will not face the same problem that you encountered.

We apologize for any frustration this may have caused, but we appreciate you taking the time to provide feedback!
