### ISSUE TITLE
Js-functions (holidayCountdown) I need some help

### ISSUE THREAD

**Issue by Stephinxs** [learn-co-curriculum/js-functions-lab#41]
// write your code below! The first 3 is correct only the last one I cannot sort out
function happyHolidays(string) {
  return "Happy holidays!"

}

function happyHolidaysTo(name) {
  return ('Happy holidays, you!')

}

function happyHolidayTo(holiday, name){
  return('Happy Independence Day, you!')
}

function holidayCountdown(holiday, days) {
  return "It\'s ${days} days until ${holiday}!"
  console.log('It\'s 20 days until Mother\'s Day!')

}

**Comment by mschute** [comment]
I was very confused about that one too. From what I had learned, the order you put your parameters in matters. Since it prints the days before the holiday, it doesn't make sense to me that the holiday parameter should be listed before the days. I typed in the function in the browser's console and if you put the holiday parameter first it prints, "It's Mother's Day days until 20!" Hmm..

**Comment by maxwellbenton** [comment]
Hi @Stephinxs,
 
We've updated the instructions to provide better guidance, specifically around template literals. Your code looks close to correct, but it looks like you used single or double quotes around each returned string, rather than backticks.

The updated instructions go into additional examples of how to use template literals and the required syntax to help ensure future students will not face the same problem that you encountered.

We apologize for any frustration this may have caused, but we appreciate you taking the time to provide feedback!
