### ISSUE TITLE
JS Functions Lab

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/js-functions-lab#45]
I seem to be having the same issue as others with this functions lab. I realized after the first 2 that something was off because my error came back with:

 1) functions happyHolidays returns "Happy holidays!":
     ReferenceError: happyHolidays is not defined
      at Context.it (test/index-test.js:6:7)
  2) functions happyHolidaysTo(name) returns "Happy holidays, ${name}!":
     ReferenceError: happyHolidaysTo is not defined
      at Context.it (test/index-test.js:12:7)
  3) functions happyHolidayTo(holiday, name) returns "Happy ${holiday}, ${name}!":
     ReferenceError: happyHolidayTo is not defined

my code:

function happyHolidaysTo(string){
  var name = "josh";
  return `Happy holidays, ${name}!`
}

function happyHolidayTo(holiday, name){
  // create var for parameters
  var holiday = "easter";
  var name = "crista";
  // return value
  return `Happy ${holiday}, ${name}!`;
}

// write a function
function holidayCountdown(holiday, days){
  // create variables
  var holiday = "Thanksgiving";
  var days = "9";
  // return value
  return `It's ${days} days until ${holiday}!`;

ANY HELP WOULD BE GREAT!

**Comment by maxwellbenton** [comment]
Hi @javonesm89,

Sorry to hear you were having difficulty with this lab. We've updated the instructions to provide better guidance, specifically around template literals. The code your provided looks close to correct. It looks like the errors you received indicate that the tests are not aware of your functions. This may also have been due to using single or double quotes instead of backticks on the template literals. We've added additional example of the required syntax for template literals to help prevent this confusion in future students.

We apologize for any frustration this may have caused, but we appreciate you taking the time to provide feedback!
